# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  database: bioheal_development
  host: localhost
  pool: 5

production:
  adapter: postgresql
  database: bioheal_production
  host: localhost
  pool: 5

test:
  adapter: postgresql
  database: bioheal_test
  host: localhost
  pool: 5